model:
  target: Models.interpretable_diffusion.FMTS.FM_TS
  params:
    seq_length: 24
    feature_size: 5
    n_layer_enc: 1
    n_layer_dec: 2
    d_model: 64  # 4 X 16
    n_heads: 4
    mlp_hidden_times: 4
    attn_pd: 0.0
    resid_pd: 0.0
    kernel_size: 1
    padding_size: 0

solver:
  base_lr: 1.0e-5
  max_epochs: 12000
  # results_folder: ./Checkpoints_sine
  gradient_accumulate_every: 2
  save_cycle: 1200  # max_epochs // 10
  ema:
    decay: 0.995
    update_interval: 10
  


dataloader:
  train_dataset:
    target: Utils.Data_utils.sine_dataset.SineDataset
    params:
      num: 10000
      dim: 5
      window: 24  # seq_length
      save2npy: True
      neg_one_to_one: True
      seed: 123
      period: train

  test_dataset:
    target: Utils.Data_utils.sine_dataset.SineDataset
    params:
      num: 1000
      dim: 5
      window: 24  # seq_length
      save2npy: True
      neg_one_to_one: True
      seed: 123
      style: separate
      period: test
      distribution: geometric
    coefficient: 1.0e-2
    step_size: 5.0e-2
    sampling_steps: 200

  batch_size: 128
  sample_size: 256
  shuffle: True